import {
  typescriptConfig,
  unicornConfig,
  workspacesConfig,
  rulesConfig,
  importConfig,
} from '@xylabs/eslint-config-flat'

const disallowedImportsXyo = [
  '@xyo-network/core-payload-plugins',
  '@xyo-network/manifest',
  '@xyo-network/modules',
  '@xyo-network/protocol',
  '@xyo-network/sdk-utils',
  '@xyo-network/shared',
  '@xyo-network/manifest-model',
  '@xyo-network/manifest-wrapper',
  '@xyo-network/boundwitness',
  '@xyo-network/core',
  '@xyo-network/crypto',
  '@xyo-network/payload',
  '@xyo-network/api',
  '@xyo-network/api-models',
  '@xyo-network/dns',
  '@xyo-network/metamask-connector',
  '@xyo-network/network',
  '@xyo-network/payload-plugin',
  '@xyo-network/payloadset-plugin',
  '@xyo-network/quadkey',
  '@xyo-network/schema-cache',
  '@xyo-network/schema-name-validator',
  '@xyo-network/witnesses',
]

const disallowedImportsXyLabs = [
  '@xylabs/api',
  '@xylabs/array',
  '@xylabs/arraybuffer',
  '@xylabs/assert',
  '@xylabs/axios',
  '@xylabs/base',
  '@xylabs/bignumber',
  '@xylabs/buffer',
  '@xylabs/creatable',
  '@xylabs/decimal-precision',
  '@xylabs/delay',
  '@xylabs/enum',
  '@xylabs/error',
  '@xylabs/eth-address',
  '@xylabs/events',
  '@xylabs/exists',
  '@xylabs/forget',
  '@xylabs/function-name',
  '@xylabs/hex',
  '@xylabs/log',
  '@xylabs/logger',
  '@xylabs/object',
  '@xylabs/platform',
  '@xylabs/profile',
  '@xylabs/promise',
  '@xylabs/retry',
  '@xylabs/set',
  '@xylabs/static-implements',
  '@xylabs/storage',
  '@xylabs/telemetry',
  '@xylabs/telemetry-exporter',
  '@xylabs/timer',
  '@xylabs/typeof',
  '@xylabs/url',
  '@xylabs/zod',
]

export default [
  { ignores: ['.yarn', '**/dist', '**/build', '**/public', '**/storybook-static', '**/.storybook', 'scripts', '**/node_modules', '.dependency-cruiser.mjs'] },
  unicornConfig,
  workspacesConfig,
  rulesConfig,
  typescriptConfig,
  {
    ...importConfig,
    rules: {
      ...importConfig.rules,
      'import-x/no-internal-modules': ['warn', { allow: ['vitest/config', 'ethers/utils', '*/index.ts', ...importConfig.rules['import-x/no-internal-modules'][1].allow] }],
      'import-x/no-unresolved': ['off'],
      'import-x/no-relative-packages': ['error'],
      'import-x/no-self-import': ['error'],
      'import-x/no-useless-path-segments': ['warn'],
      'sonarjs/prefer-single-boolean-return': ['off'],
    },
  },
  {
    files: ['**/packages/*/src/**/*.{js,ts}'],
    ignores: ['**/*.spec.{js,ts}', 'packages/sdk/src/test/**/*', 'packages/cli/src/**/*'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            ...disallowedImportsXyLabs,
            ...disallowedImportsXyo,
          ],
        },
      ],
    },
  },
  {
    rules: {
      '@stylistic/max-len': ['warn', { code: 200 }],
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_', varsIgnorePattern: '^_', ignoreRestSiblings: true,
        },
      ],
    },
  },
]
