export const XL1_PROTOCOL_VERSION_MAJOR = 1 as const
export const XL1_PROTOCOL_VERSION_MINOR = 2 as const
export const XL1_PROTOCOL_VERSION_PATCH = 0 as const
export const XL1_PROTOCOL_VERSION_STRING = `${XL1_PROTOCOL_VERSION_MAJOR}.${XL1_PROTOCOL_VERSION_MINOR}.${XL1_PROTOCOL_VERSION_PATCH}` as const
export const XL1_PROTOCOL_VERSION = XL1_PROTOCOL_VERSION_MAJOR * 1_000_000 + XL1_PROTOCOL_VERSION_MINOR * 1000 + XL1_PROTOCOL_VERSION_PATCH
